// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Bai_Jamjuree } from "next/font/google";

const bai = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Apply Bai Jamjuree site-wide */}
      <body className={`${bai.className} antialiased`}>{children}</body>
    </html>
  );
}
